---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dmz-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dmz-app
  template:
    metadata:
      labels:
        app: dmz-app
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.12
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dmz-service
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 80
      targetPort: 80
  selector:
    app: dmz-app
