---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mz-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mz-app
  template:
    metadata:
      labels:
        app: mz-app
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.12
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mz-service
spec:
  type: LoadBalancer
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 80
      targetPort: 80
  selector:
    app: mz-app
